### ISSUE TITLE
Autentication broken

### ISSUE THREAD

**Issue by norbergmats** [kevinVl/NissanConnect#8]
2024-05-16.
It seems like the autentication broke down. Suddenly it seems like the NissanConnect-Session sub flow wont work anymore.
"TypeError: Cannot read properties of undefined (reading 'split')"
It worked the day before 2024-05-15. Any other persons having issues ?

**Comment by kevinVl** [comment]
To fix, the node red flows, you will need to change some config in the authentication nodes : 

![image](https://github.com/kevinVl/NissanConnect-HomeAssistant/assets/6417524/2ba324c9-d8e3-486e-a1ed-0bc45018b6d3)

Set client-id : a-ncb-nc-android-prod
and  client-secret to  : 6GKIax7fGT5yPHuNmWNVOc4q5POBw1WRSW39ubRA8WPBmQ7MOxhm75EsmKMKENem



once done and deployed, refresh the tokens by activating the timestamp triggers.
